### ISSUE TITLE
Controller uses out of date API

### ISSUE THREAD

**Issue by YiannisGkoufas** [kubernetes-sigs/container-object-storage-interface-controller#39]
# Bug Report

**What happened**:

Deployed all the COSI components and the sample provisioner for Minio.
Created a BucketClass and a Bucket Request.
Got the error:
```
E0225 15:06:33.702088       1 bucketrequest.go:85] error getting bucketclass: [&{{BucketClass objectstorage.k8s.io/v1alpha1} {my-bucketclass    98a672fd-dd77-4a04-9e06-0d3cbaf7c851 17330 1 2021-02-25 15:06:28 +0000 UTC <nil>  map[] map[] [] []  [{kubectl-create Update objectstorage.k8s.io/v1alpha1 2021-02-25 15:06:28 +0000 UTC FieldsV1 {"f:isDefaultBucketClass":{},"f:protocol":{".":{},"f:name":{},"f:s3":{".":{},"f:bucketName":{},"f:endpoint":{},"f:region":{}}},"f:provisioner":{},"f:retentionPolicy":{}}}]} false []  {false false false false}  map[] }] v1alpha1.BucketClass.Protocol: ReadString: expects " or n, but found {, error found in #10 byte of ...|rotocol":{"name":"s3|..., bigger context ...|8a672fd-dd77-4a04-9e06-0d3cbaf7c851"},"protocol":{"name":"s3","s3":{"bucketName":"my-bucket","endpoi|...
I0225 15:06:33.702173       1 bucketrequest.go:47] BucketClass specified does not exist while processing BucketRequest bucket-request.
```
I believe this happens because the image hosted on quay.io/containerobjectstorage/objectstorage-controller is old.

**What you expected to happen**:

To create a Bucket object

**How to reproduce this bug (as minimally and precisely as possible)**:

Install all COSI components and sample provisioner:
```bash
kubectl create -k github.com/kubernetes-sigs/container-object-storage-interface-api
kubectl create -k github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter
kubectl create -k github.com/kubernetes-sigs/container-object-storage-interface-controller
kubectl create -k github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar
```
Create the BucketClass and the BucketRequest:
```
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClass
metadata:
  name: my-bucketclass
provisioner: "sample-provisioner.objectstorage.k8s.io-dev"
protocol:
  name: "s3"
  s3:
    endpoint: "minio-service.minio-ns:9000"
    bucketName: "my-bucket"
    region: ""
---
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketRequest
metadata:
  name: bucket-request
spec:
  bucketPrefix: "cosi"
  bucketClassName: "my-bucketclass"
```

**Environment**:

Minikube
